services:
  cloudmanager:
    container_name: cloudmanager
    image: cakhullab/cloudmanager:latest
    networks:
      - cloudmanager
    ports:
      - 8000:80
    volumes:
      - /home/cak-hul/Documents:/srv
      - cloudmanager_db:/database
    environment:
      - FB_REDIS_CACHE_URL=redis://default:filebrowser@redis:6379 # Use rediss:// for ssl

  redis:
    container_name: redis
    image: redis:latest
    networks:
      - cloudmanager
    command:
      - sh
      - -c
      - |
        cat > /tmp/users.acl <<EOF
        user default on >cloudmanager ~* +@all
        EOF
        redis-server --aclfile /tmp/users.acl

networks:
  cloudmanager:

volumes:
  cloudmanager:
  cloudmanager_db:
